# This file is only used in the development enviroment

version: '3.3'
services:
  pict_api:
    build: .
    environment:
      NODE_ENV: development
    container_name: pict_api
    command: bash -c 'yarn && yarn test' # `yarn` to also install dev packages
    volumes:
      # overwrite existing files in docker image with local file
      - .:/root/api
      - /root/api/node_modules/
    working_dir: /root/api
    ports:
      - '8080:8080'
  # pict_react:
  #   image: node:12.12.0-alpine
  #   container_name: pict_react
  #   volumes:
  #     - ./front:/root/front
  #     - /root/front/node_modules/
  #   working_dir: /root/front
  #   depends_on:
  #     - pict_api
  #   ports:
  #     - '3000:3000'
  #   command: sh -c 'yarn && yarn start'
