version: 2
jobs:
  backend:
    docker:
      - image: docker:19.03.4-git
    working_directory: /app
    steps:
      # https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --target target_for_compilation -t app .
      - run:
          name: Test Docker image
          command: docker run -it --rm app bash -c "go test"
  frontend:
    docker:
      - image: circleci/node:12.12.0-buster
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "front/yarn.lock" }}
      - run:
          name: Fetch libraries
          command: cd front && yarn
      - save_cache:
          paths:
            - ~/app/front/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "front/yarn.lock" }}
      - run:
          name: Build frontend app
          command: cd front && yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend
      - frontend
